### ISSUE TITLE
Talk: Normalizing Flows

### ISSUE THREAD

**Issue by euler16** [mohitsharma29/ML-Reading-Group#6]
Landmark Paper for Variational Inference: [Variational Inference with Normalizing Flows](https://arxiv.org/pdf/1505.05770v6.pdf)<br/>

Crisp description of the method: [PaperswithCode.com](https://paperswithcode.com/method/normalizing-flows)

Slides: Will be added soon

Prerequisites: Basic Probability theory, basic calculus.

**Comment by mohitsharma29** [comment]
Hey, can you attach the relevant blog posts that you used during your presentation and close this issue?

**Comment by euler16** [comment]
http://akosiorek.github.io/ml/2018/04/03/norm_flows.html
https://deepgenerativemodels.github.io/notes/flow/
https://www.youtube.com/watch?v=i7LjDvsLWCg
http://proceedings.mlr.press/v37/rezende15.pdf
