### ISSUE TITLE
Talk: Active Learning

### ISSUE THREAD

**Issue by pcharul** [mohitsharma29/ML-Reading-Group#8]
Few of the papers I find useful:

1. Active Learning for Convolutional Neural Networks: A Core-Set Approach(https://arxiv.org/pdf/1708.00489.pdf) 
2. Submodularity in Data Subset Selection and Active Learning (http://proceedings.mlr.press/v37/wei15.pdf)
3. Deep Bayesian Active Learning with Image Data (https://arxiv.org/pdf/1703.02910.pdf)
4.  Adversarial Active Learning for Deep Networks: a Margin Based Approach (https://arxiv.org/pdf/1802.09841.pdf)
5. Active Learning Literature Survey (2010)(http://burrsettles.com/pub/settles.activelearning.pdf)

Slides: Will be added soon

**Comment by mohitsharma29** [comment]
Hey, can you attach your slides and close this issue?

**Comment by pcharul** [comment]
The slides are available [here](https://drive.google.com/file/d/1LrJtysz0dHzNjOv42rTbLqjWo2L5panQ/view?usp=sharing)
